name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: eminent-bond-459020-q4
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker for Google Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and push Docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/eminent-bond-459020-q4/fastapi-app/fastapi-app:latest .
          docker push us-central1-docker.pkg.dev/eminent-bond-459020-q4/fastapi-app/fastapi-app:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy fastapi-api \
            --image us-central1-docker.pkg.dev/eminent-bond-459020-q4/fastapi-app/fastapi-app:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
