name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: eminent-bond-459020-q4
  SERVICE_NAME: fastapi-api
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    
    - name: Authenticate Docker to Google Cloud
      run: gcloud auth configure-docker gcr.io
    
    - name: Build and push Docker image
      run: |
        docker build --platform linux/amd64 -t gcr.io/$PROJECT_ID/fastapi-app:${{ github.sha }} .
        docker push gcr.io/$PROJECT_ID/fastapi-app:${{ github.sha }}
    
    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: ${{ env.SERVICE_NAME }}
        region: ${{ env.REGION }}
        image: gcr.io/${{ env.PROJECT_ID }}/fastapi-app:${{ github.sha }}
        flags: --allow-unauthenticated